application: neurodatafame
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: asklogin.app
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'django_settings'

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest